### ISSUE TITLE
Torrent info_hash is not correct

### ISSUE THREAD

**Issue by 0x413x** [UNIT3D/UNIT3D#111]
- Laravel Version: 5.4.36
- PHP Version: 7.1.13-1
- Database Driver & Version: MySQL 5.7

### Description:
Torrent info_hash is not correct

[snapshot](https://imgur.com/a/R5tSP)

### Steps To Reproduce:
Upload a torrent to site, and check client error msg

### Possible Fix:
Maybe "app/Services/Bencode.php" is not functional?

I have a script is correct for info_hash, with torrent file for test.
[xx.php](https://drop.usestak.com/share/suV31515615209q7S4)
[Transmission-2.92.dmg.torrent](https://drop.usestak.com/share/0pXP1515614799s3oX)

**Comment by HDVinnie** [comment]
Did you redownload the new torrent file from UNIT3D after uploading? You must do that since source flag is set as seen in PR #76 . From what I can see and from testing everything is functional.

**Comment by HDVinnie** [comment]
Was that your issue?

**Comment by 0x413x** [comment]
It's work. Thanks for your help.
