### ISSUE TITLE
Can not update app.php -> url value via staff dashboard

### ISSUE THREAD

**Issue by VerioPL** [UNIT3D/UNIT3D#115]
- Laravel Version: 5.4.36
- PHP Version: 7.1.13 FPM
- Database Driver & Version: mysql | mysql 5.7.21 (community)

### Description:
Can not update "url" value, I get 500 error in ajax response what says:

(1/1) ExceptionUnable to rewrite key "url" in config, rewrite failed
--
in Rewrite.php (line 53)
at Rewrite->toContent(' **[here is app.php content]**' => [ /* * Laravel Framework Service Providers... */ Illuminate\\Auth\\AuthServiceProvider::class, Illuminate\\Broadcasting\\BroadcastServiceProvider::class, Illuminate\\Bus\\BusServiceProvider::class, Illuminate\\Cache\\CacheServiceProvider::class, Illuminate\\Foundation\\Providers\\ConsoleSupportServiceProvider::class, Illuminate\\Cookie\\CookieServiceProvider::class, Illuminate\\Database\\DatabaseServiceProvider::class, Illuminate\\Encryption\\EncryptionServiceProvider::class, Illuminate\\Filesystem\\FilesystemServiceProvider::class, Illuminate\\Foundation\\Providers\\FoundationServiceProvider::class, Illuminate\\Hashing\\HashServiceProvider::class, Illuminate\\Mail\\MailServiceProvider::class, Illuminate\\Notifications\\NotificationServiceProvider::class, Illuminate\\Pagination\\PaginationServiceProvider::class, Illuminate\\Pipeline\\PipelineServiceProvider::class, Illuminate\\Queue\\QueueServiceProvider::class, Illuminate\\Redis\\RedisServiceProvider::class, Illuminate\\Auth\\Passwords\\PasswordResetServiceProvider::class, Illuminate\\Session\\SessionServiceProvider::class, Illuminate\\Translation\\TranslationServiceProvider::class, Illuminate\\Validation\\ValidationServiceProvider::class, Illuminate\\View\\ViewServiceProvider::class, /* * Package Service Providers... */ Laravel\\Tinker\\TinkerServiceProvider::class, Collective\\Html\\HtmlServiceProvider::class, Spatie\\CookieConsent\\CookieConsentServiceProvider::class, Brian2694\\Toastr\\ToastrServiceProvider::class, Hootlex\\Moderation\\ModerationServiceProvider::class, Arcanedev\\LogViewer\\LogViewerServiceProvider::class, Gstt\\Achievements\\AchievementsServiceProvider::class, Infinety\\ConfigManager\\ConfigManagerServiceProvider::class, Bepsvpt\\SecureHeaders\\SecureHeadersServiceProvider::class, ChristofferOK\\LaravelEmojiOne\\LaravelEmojiOneServiceProvider::class, Way\\Generators\\GeneratorsServiceProvider::class, Xethron\\MigrationsGenerator\\MigrationsGeneratorServiceProvider::class, Kyslik\\ColumnSortable\\ColumnSortableServiceProvider::class, RenatoMarinho\\LaravelPageSpeed\\ServiceProvider::class, Intervention\\Image\\ImageServiceProvider::class, /* * Application Service Providers... */ App\\Providers\\AppServiceProvider::class, App\\Providers\\AuthServiceProvider::class, // App\\Providers\\BroadcastServiceProvider::class, App\\Providers\\EventServiceProvider::class, App\\Providers\\RouteServiceProvider::class, ], /*	\|--------------------------------------------------------------------------	\| Class Aliases	\|--------------------------------------------------------------------------	\|	\| This array of class aliases will be registered when this application	\| is started. However, feel free to register as many as you wish as	\| the aliases are "lazy" loaded so they don\'t hinder performance.	\|	*/ \'aliases\' => [ \'App\' => Illuminate\\Support\\Facades\\App::class, \'Artisan\' => Illuminate\\Support\\Facades\\Artisan::class, \'Auth\' => Illuminate\\Support\\Facades\\Auth::class, \'Blade\' => Illuminate\\Support\\Facades\\Blade::class, \'Broadcast\' => Illuminate\\Support\\Facades\\Broadcast::class, \'Bus\' => Illuminate\\Support\\Facades\\Bus::class, \'Cache\' => Illuminate\\Support\\Facades\\Cache::class, \'Config\' => Illuminate\\Support\\Facades\\Config::class, \'Cookie\' => Illuminate\\Support\\Facades\\Cookie::class, \'Crypt\' => Illuminate\\Support\\Facades\\Crypt::class, \'DB\' => Illuminate\\Support\\Facades\\DB::class, \'Eloquent\' => Illuminate\\Database\\Eloquent\\Model::class, \'Event\' => Illuminate\\Support\\Facades\\Event::class, \'File\' => Illuminate\\Support\\Facades\\File::class, \'Gate\' => Illuminate\\Support\\Facades\\Gate::class, \'Hash\' => Illuminate\\Support\\Facades\\Hash::class, \'Lang\' => Illuminate\\Support\\Facades\\Lang::class, \'Log\' => Illuminate\\Support\\Facades\\Log::class, \'Mail\' => Illuminate\\Support\\Facades\\Mail::class, \'Notification\' => Illuminate\\Support\\Facades\\Notification::class, \'Password\' => Illuminate\\Support\\Facades\\Password::class, \'Queue\' => Illuminate\\Support\\Facades\\Queue::class, \'Redirect\' => Illuminate\\Support\\Facades\\Redirect::class, \'Redis\' => Illuminate\\Support\\Facades\\Redis::class, \'Request\' => Illuminate\\Support\\Facades\\Request::class, \'Response\' => Illuminate\\Support\\Facades\\Response::class, \'Route\' => Illuminate\\Support\\Facades\\Route::class, \'Schema\' => Illuminate\\Support\\Facades\\Schema::class, \'Session\' => Illuminate\\Support\\Facades\\Session::class, \'Storage\' => Illuminate\\Support\\Facades\\Storage::class, \'URL\' => Illuminate\\Support\\Facades\\URL::class, \'Validator\' => Illuminate\\Support\\Facades\\Validator::class, \'View\' => Illuminate\\Support\\Facades\\View::class, \'Form\' => Collective\\Html\\FormFacade::class, \'Html\' => Collective\\Html\\HtmlFacade::class, \'CookieConsent\' => BrianFaust\\CookieConsent\\Facades\\CookieConsent::class, \'Toastr\' => Brian2694\\Toastr\\Facades\\Toastr::class, \'LaravelEmojiOne\' => ChristofferOK\\LaravelEmojiOne\\LaravelEmojiOneFacade::class, \'Image\' => Intervention\\Image\\Facades\\Image::class, \'LogActivity\' => App\\Helpers\\LogActivity::class, ],];',array('url' => '**[domain]**'), true)in Rewrite.php (line 28)
at Rewrite->toFile('/var/www/html/**[domain]**/config/app.php', array('url' => '**[domain]**'))in ConfigHelper.php (line 72)
at ConfigHelper->save('app.php', 'url', '[domain]')in Facade.php (line 221)
at Facade::__callStatic('save', array('app.php', 'url', '**[domain]**'))in ConfigManagerController.php (line 52)
at ConfigManagerController->update(object(Request))
at call_user_func_array(array(object(ConfigManagerController), 'update'), array(object(Request)))in Controller.php (line 55)
at Controller->callAction('update', array(object(Request)))in ControllerDispatcher.php (line 44)
at ControllerDispatcher->dispatch(object(Route), object(ConfigManagerController), 'update')in Route.php (line 203)
at Route->runController()in Route.php (line 160)
at Route->run()in Router.php (line 572)
at Router->Illuminate\Routing\{closure}(object(Request))in Pipeline.php (line 30)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in CheckForAdmin.php (line 34)
at CheckForAdmin->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in Http2ServerPush.php (line 39)
at Http2ServerPush->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in CheckIfOnline.php (line 35)
at CheckIfOnline->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in VerifyCsrfToken.php (line 65)
at VerifyCsrfToken->handle(object(Request), object(Closure))in VerifyCsrfToken.php (line 30)
at VerifyCsrfToken->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in SubstituteBindings.php (line 41)
at SubstituteBindings->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in Authenticate.php (line 43)
at Authenticate->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in ShareErrorsFromSession.php (line 49)
at ShareErrorsFromSession->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in StartSession.php (line 64)
at StartSession->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in AddQueuedCookiesToResponse.php (line 37)
at AddQueuedCookiesToResponse->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in EncryptCookies.php (line 59)
at EncryptCookies->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in Pipeline.php (line 102)
at Pipeline->then(object(Closure))in Router.php (line 574)
at Router->runRouteWithinStack(object(Route), object(Request))in Router.php (line 533)
at Router->dispatchToRoute(object(Request))in Router.php (line 511)
at Router->dispatch(object(Request))in Kernel.php (line 176)
at Kernel->Illuminate\Foundation\Http\{closure}(object(Request))in Pipeline.php (line 30)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in SecureHeadersMiddleware.php (line 21)
at SecureHeadersMiddleware->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in TransformsRequest.php (line 30)
at TransformsRequest->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in TransformsRequest.php (line 30)
at TransformsRequest->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in ValidatePostSize.php (line 27)
at ValidatePostSize->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in CheckForMaintenanceMode.php (line 46)
at CheckForMaintenanceMode->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in Pipeline.php (line 102)
at Pipeline->then(object(Closure))in Kernel.php (line 151)
at Kernel->sendRequestThroughRouter(object(Request))in Kernel.php (line 116)
at Kernel->handle(object(Request))in index.php (line 52)

### Steps To Reproduce:
As in title
Provided new value is in format https://sub.domain.tld

**Comment by HDVinnie** [comment]
You need to set correct permissions for the config directory and files within. that appears to be your issue. let me know how you make out.

**Comment by HDVinnie** [comment]
# Change owner of storage, bootstrap and config laravel directories
`cd /var/www/html`  <---or wherever UNIT3D is on your server.
`sudo chown -R www-data: storage bootstrap config`

**Comment by VerioPL** [comment]
It's absolutely the same effect

**Comment by HDVinnie** [comment]
Ok well if what I  suggested above does not work then I am not sure I have done multiple installs and have never had this issue. But the error clearly shows it's a permissions error. I'm assuming you are not running this in production. So might I suggest trying to change the permissions of the config directory in all files within to 777. If that works which I don't recommend keeping it that way it confirms that it's a permissions error on your end.

**Comment by VerioPL** [comment]
I just used chmod 777 -R /www/[domain]/config and it's make still error. I checked also selinux but it is set in permissive mode.

**Comment by HDVinnie** [comment]
I will be home in 2 hours and will try to replicate this issue and find out what the issue is. So if I understand correctly you can edit other config files fine including the app.php config besides that one value for URL. However now just looking that value is supposed to be set by you before installing directly in the .env file.  As described in the README install instructions. It is currently not formatted properly to work from the config manager.

**Comment by VerioPL** [comment]
Please close that issue. I made error in virtualhost configuration (it was pointing wrong DirectoryRoot). Really sorry for my inconvenience.

**Comment by HDVinnie** [comment]
Not a problem. Glad it was solved.
