### ISSUE TITLE
Error exception on register

### ISSUE THREAD

**Issue by rickfo97** [UNIT3D/UNIT3D#13]
- Laravel Version: 5.4.*
- PHP Version: 7.0.22-0
- Database Driver & Version: mysql 5.7.20-0

### Description:
When you register a new user it displays an exception with the message "Creating default object from empty value" at line 78 in "RegisterController.php"

### Steps To Reproduce:
Go to sign up without invite.
Enter details.
Click signup.
Exception displays.

### Possible Fix:
Check if $key is set before accessing it.

**Comment by HDVinnie** [comment]
I ran multiple test against this with config/other.php 'invite-only' => true and false. I could not find anymore issues. If I did however miss something please let me know so.
