### ISSUE TITLE
Shoutbox error

### ISSUE THREAD

**Issue by rickfo97** [UNIT3D/UNIT3D#14]
- Laravel Version: 5.4.*
- PHP Version: 7.0.22-0
- Database Driver & Version: mysql 5.7.20-0

### Description:
When a shoutbox message has the user 0 an exception is displayed

### Steps To Reproduce:
Have a message in the shoutbox table by user id 0.
Go to "[url]/".

### Possible Fix:
Check if $messages->user is 0

**Comment by HDVinnie** [comment]
$user->id of 0 is for the System account which posts the System Auto Shouts.
$user->id of 1 is for the Bot account which posts the Random Site Nerd Stats.
$user->id of 2 is default owner account.
id's increment from there.

do you have these in you DB? As im not seeing this issue.

**Comment by poppabear8883** [comment]
I did not realize that it required a specific set of id's i will work on this now

**Comment by HDVinnie** [comment]
This goes in hand with #10
