### ISSUE TITLE
WysiBB textarea require error

### ISSUE THREAD

**Issue by VerioPL** [UNIT3D/UNIT3D#146]
- UNIT3D Version: latest
- Laravel Version: latest
- PHP Version: 7.1
- Database Driver & Version: mysql 5.7

### Description:
In upload form when adding new torrent and clicking submit button nothing happens. In developers console is I can see:
An invalid form control with name='description' is not focusable. upload:1
Probably error is in another textareas.

### Possible Fix:
Probably turning off required param for textareas.
https://www.google.pl/search?q=textarea+required+is+not+focusable

**Comment by VerioPL** [comment]
Browser is Vivaldi based on Chromium engine

**Comment by VerioPL** [comment]
After manual remove "required" param in developers console form can be submitted.

**Comment by HDVinnie** [comment]
I fix this......seems cross browser issue as I didn't have this when I first committed the changes and tested on safari.
