### ISSUE TITLE
Add tag v1.0 to commit 5a32c2c

### ISSUE THREAD

**Issue by brolaugh** [UNIT3D/UNIT3D#15]
- Laravel Version: N/A
- PHP Version: N/A
- Database Driver & Version: N/A

### Description:
The commit 5a32c2c should be tagged with `v1.0` to mark it as an important point of time for the repository.

### Steps To Reproduce:
N/A

### Possible Fix:
This can only be done by someone who has write access to the repository.

```
git tag -a v1.0 5a32c2c -m "Initial Release"
git push --tags
```

**Comment by Hyleus** [comment]
Done.

**Comment by brolaugh** [comment]
Consider making a the tag into a  Github release with a changelog.
