### ISSUE TITLE
Missing info_hash bug!

### ISSUE THREAD

**Issue by krisztinzoltan** [UNIT3D/UNIT3D#164]
Laravel Version: 5.5.31
    PHP Version: PHP 7.1.13
    Database Driver & Version: mysql  Ver 14.14 Distrib 5.7.20

Add torrentfile to utorrent.

error " Missing info_hash " 

https://imgur.com/a/7wsNw

**Comment by HDVinnie** [comment]
This issue does not follow our issue template. Fix it and give proper info or it will be closed. 

https://github.com/UNIT3D/UNIT3D/blob/master/ISSUE_TEMPLATE.md

**Comment by HDVinnie** [comment]
Again does not follow guidelines.....your giving no info on this issue.
