### ISSUE TITLE
Trying to get property of non-object $requestClaim->anon

### ISSUE THREAD

**Issue by VerioPL** [UNIT3D/UNIT3D#173]
- UNIT3D Version: latest
- Laravel Version: latest
- PHP Version: 7.1
- Database Driver & Version: mysql 5.7

### Description:
/var/www/html/dev/storage/framework/views/d9920cdac65ae307b25d2e0cbdee0f30174d5507.php
              <button class="btn btn-xs btn-success" disabled><i class="fa fa-check-square-o"></i>Filled</button>
              <?php else: ?> <?php if(**$requestClaim->anon** == 0): ?>
              <span class="badge-user"><?php echo e($requestClaim->username); ?></span> <?php if($user->group->is_modo || $requestClaim->username == $user->username): ?>

### Steps To Reproduce:
1. Make request
2. Claim self-created reqest (as anonymous or not)
3. View request
4. Click on reset claim

### Possible Fix:
i don't know :(

**Comment by VerioPL** [comment]
View builded from /var/www/html/dev/resources/views/requests/request.blade.php)

**Comment by VerioPL** [comment]
In DB left request, but request_claims is empty. So unclaim is working correctly

**Comment by HDVinnie** [comment]
I'm having trouble replicating this but will test more when home tonight.

**Comment by VerioPL** [comment]
If you want I can share you my environment and account, PM me on discord if you are interested

**Comment by VerioPL** [comment]
I maked all db dump before and after clicking "reset claim", this is diff:

`diff dump1.sql dump2.sql
1206d1205
< INSERT INTO `request_claims` VALUES (1,1,'Administrator',0,'2018-02-05 13:49:04','2018-02-05 13:49:04');
1257c1256
< INSERT INTO `requests` VALUES (1,'sample request',1,'UHD-100','0396171','0','0','0','tt0396171',3,100.00,1,1,'2018-02-05 13:48:56','2018-02-05 13:49:04',NULL,NULL,NULL,NULL,NULL);
---
> INSERT INTO `requests` VALUES (1,'sample request',1,'UHD-100','0396171','0','0','0','tt0396171',3,100.00,1,**0**,'2018-02-05 13:48:56','2018-02-05 13:49:37',NULL,NULL,NULL,NULL,NULL);
1776c1775
< -- Dump completed on 2018-02-05 15:49:31
---
> -- Dump completed on 2018-02-05 15:49:47
`
