### ISSUE TITLE
XBTIT Upgrade Script

### ISSUE THREAD

**Issue by HDVinnie** [UNIT3D/UNIT3D#19]
- Laravel Version: #.#.#
- PHP Version:
- Database Driver & Version:

### Description:
Looking for someone that can make a script to port over a xbtit database dump into UNIT3D. Im thinking mainly torrents and users are most important and probably only ones worth it? Thoughts? 

### Steps To Reproduce:
N/A

### Possible Fix:
N/A

**Comment by Hyleus** [comment]
If possible write it in PHP, so that no extra programs beyond the server requirements must be used.

**Comment by pxgamer** [comment]
I also started this here:
https://github.com/pxgamer/xbtit-to-unit3d/tree/develop

There are a couple of things I'm looking into though. Mainly how to insert using data from a package (during unit tests, etc.)

**Comment by HDVinnie** [comment]
this is exciting....thanks @pxgamer

**Comment by pxgamer** [comment]
I've tested a bit, and the package seems to be working but I'd need an in-depth database to test with.

I'll keep looking into this.

**Comment by HDVinnie** [comment]
I have a xbtitFM DB dump I can pass on to you tomorrow

**Comment by HDVinnie** [comment]
tested and working
