### ISSUE TITLE
U-232 Upgrade Script

### ISSUE THREAD

**Issue by HDVinnie** [UNIT3D/UNIT3D#23]
- Laravel Version: #.#.#
- PHP Version:
- Database Driver & Version:

### Description:
Looking for someone that can make a script to port over a u-232 database dump into UNIT3D. Im thinking mainly torrents and users are most important and probably only ones worth it? Thoughts?

### Steps To Reproduce:
N/A

### Possible Fix:
N/A

**Comment by Hyleus** [comment]
If possible write it in PHP, so that no extra programs beyond the server requirements must be used.

**Comment by pxgamer** [comment]
Added in https://github.com/pxgamer/u232-to-unit3d

I've tested it mostly, but would be good to have an example database to test with to make sure.

**Comment by HDVinnie** [comment]
tested and working
