### ISSUE TITLE
Localize UNIT3D in more languages

### ISSUE THREAD

**Issue by Hyleus** [UNIT3D/UNIT3D#25]
- Laravel Version: #.#.#
- PHP Version: N/A
- Database Driver & Version: N/A

### Description:
It would be nice to add more translations to UNIT3D, currently only English is supported. If you can translate it in your language, just leave a reply here.

Current translations:
French (100%)
German (70%)

### Steps To Reproduce:
N/A

### Possible Fix:
N/A

**Comment by HDVinnie** [comment]
French is done 45854d5588fe988041b6217ddbbf39e1c3ccef25

**Comment by ScroogeHD117** [comment]
I can do Dutch and Afrikaans. 

I'm a Github noob, do I just start working on it and then request a pull?

**Comment by acomerlatto** [comment]
I can do Portuguese-Brazil (PT-BR).
I'll start tomorrow! :)

**Comment by Hyleus** [comment]
Thanks, when possible do the translation in one single PR.
