### ISSUE TITLE
Upload Page Improvements

### ISSUE THREAD

**Issue by xdamanx** [UNIT3D/UNIT3D#28]
- Laravel Version: #.#.#
- PHP Version:
- Database Driver & Version:

### Description:

Improve the user upload page to take in more information from the user. Consider adding fields such as year, trailer link, source (Bluray, DVD, WEB, etc.), codec (XviD, Divx, x264, H.264, BD50, etc.), container (mkv, avi, mp4, etc.), resolution (720p, 1080p, 4k, etc.), and genre tags (action, comedy, etc.).

Possibly also consider providing checkboxes for whether it is a scene release, whether it includes subtitles, and whether it is a personal rip.

Also consider implementing the ability to add an .nfo file to the upload page.

**Comment by HDVinnie** [comment]
adding more work for uploads is not a good look. Users want simplicity. Plus everything you suggested exists or is pointless....

1) year, trailer link ---> already provided by API system
2) source (Bluray, DVD, WEB, etc.) ---> no point. any proper tracker will require it in torrent name schema.
3) codec (XviD, Divx, x264, H.264, BD50, etc.) ---> no point. any proper tracker will require it in torrent name schema.
4) container (mkv, avi, mp4, etc.) ---> no point. any proper tracker will require it in torrent name schema.
5) resolution (720p, 1080p, 4k, etc.) ---> thats what the types dropdown is for.
6) genre tags (action, comedy, etc.) ---> already provided by API system

7) Also consider implementing the ability to add an .nfo file to the upload page.  ---> already is its just being reworked.

**Comment by xdamanx** [comment]
Ok perhaps I went about these suggestions the wrong way. Being able to grab that information form an API is great and if we can do that automatically then it is the best cased scenario.

Now maybe instead you could implement the ability to sort/search torrents based on the above criteria. Suppose you want to browse for 2014 action movies in 720p resolution. Would it be possible to implement the ability to search for something like that?

**Comment by HDVinnie** [comment]
Have you even loaded up the site and played with it?

Again any proper tracker will require the year in torrent name schema. 

Like:
" Dunkirk 2017 Bluray 1080p DTS-HDMA 5.1 x264 - GroupTag "

So yes you can already search like that....
https://imgur.com/d8RGp9U

Please have reviewed the codebase in full before submitting issues to avoid wasteful time. The only think I see valid would be a actual genres system that ties into the faceted search system. That in itself is one request(issue).
