### ISSUE TITLE
Table Migration issue

### ISSUE THREAD

**Issue by zeealiawan** [UNIT3D/UNIT3D#39]
after installing everything above successfully i have encountered this problem when i run this command

(php artisan migrate --seed)

output:

In Connection.php line 647:

  could not find driver (SQL: select * from information_schema.tables where t
  able_schema = my720_un1 and table_name = migrations)

In PDOConnection.php line 47:

  could not find driver

In PDOConnection.php line 43:

  could not find driver

Any Suggestion

**Comment by Hyleus** [comment]
What Webserver are you using? It might be that you're missing a module here for MySQL support. When you're using Linux name your distro.

**Comment by zeealiawan** [comment]
Server version: Apache/2.4.29 (cPanel)

PHP 7.1   mysql 5.6  Redis server v=3.9.103

i have installed all extensions that were require for this and i solve this problem now new problem encountered with this command:

php artisan migrate --seed

**output:**

In Connection.php line 647:

  SQLSTATE[42S01]: Base table or view already exists: 1050 Table 'achievement
  _details' already exists (SQL: create table `achievement_details` (`id` int
   unsigned not null auto_increment primary key, `name` varchar(255) not null
  , `description` varchar(255) not null, `points` int unsigned not null defau
  lt '1', `secret` tinyint(1) not null default '0', `class_name` varchar(255)
   not null, `created_at` timestamp null, `updated_at` timestamp null) defaul
  t character set utf8mb4 collate utf8mb4_unicode_ci)


In PDOStatement.php line 107:

  SQLSTATE[42S01]: Base table or view already exists: 1050 Table 'achievement
  _details' already exists


In PDOStatement.php line 105:

  SQLSTATE[42S01]: Base table or view already exists: 1050 Table 'achievement
  _details' already exists

**Comment by zeealiawan** [comment]
I have found the solution here

change code of this file (app/Providers/AppServiceProvider.php)  with code given below:

> <?php namespace App\Providers;

use Illuminate\Support\ServiceProvider;

use Illuminate\Support\Facades\Schema;

class AppServiceProvider extends ServiceProvider
{

    /**
     * Bootstrap any application services.
     *
     * @return void
     */
    public function boot()
    {
        Schema::defaultStringLength(191);
    }

    /**
     * Register any application services.
     *
     * This service provider is a great spot to register your various container
     * bindings with the application. As you can see, we are registering our
     * "Registrar" implementation here. You can add your own bindings too!
     *
     * @return void
     */
    public function register()
    {
    }
}

**Comment by Hyleus** [comment]
Could you try to install the newest version of MySQL?

**Comment by zeealiawan** [comment]
i try but error still exists then i add couple of lines in AppServiceProvider.php and it worked like charm no error

**Comment by zeealiawan** [comment]
does this cms support udp external trackers ????

**Comment by Hyleus** [comment]
Please open a Issue for every question you have. I've removed your comment because it has nothing to do with "Table Migration issue."

**Comment by D3monCoder** [comment]
To fix this go to config/database.php line 59
find:
`            'charset' => 'utf8mb4',
            'collation' => 'utf8mb4_unicode_ci',`

Change it to:
`            'charset' => 'utf8',
            'collation' => 'utf8_unicode_ci',`
drop previous database before run the command again

**Comment by HDVinnie** [comment]
That is not the proper solution. 

'charset' => 'utf8mb4', 'collation' => 'utf8mb4_unicode_ci',

Is what you should be using. I will look into this.

**Comment by HDVinnie** [comment]
@zeealiawan use MySQL 5.7.7 or greater and your good to go. You SHOULDNT be changing the ```config/database.php``` or ```App/Providers/AppServiceProvider.php```
