### ISSUE TITLE
No Ability to Edit Torrent Comments/Article Comments

### ISSUE THREAD

**Issue by Red227** [UNIT3D/UNIT3D#50]
- Laravel Version: N/A
- PHP Version: N/A
- Database Driver & Version: N/A

### Description: 
There is no ability to edit comments for either the user that wrote them or Staff. Just the option to delete them.

### Steps To Reproduce:
Make a comment on a torrent description or article. Save it. 

### Possible Fix:
Add the option to be able to delete or edit comments on torrent descriptions and articles.

**Comment by Hyleus** [comment]
I've fixed the markdown formatting of that suggestion.
