### ISSUE TITLE
Request

### ISSUE THREAD

**Issue by zeealiawan** [UNIT3D/UNIT3D#52]
- Laravel Version: #.#.#
- PHP Version:
- Database Driver & Version:

### Description:

your torrent tracker cms is awesome thats why i want to use it for my site. i am starting a new torrent public site like rarbg.to and 1337x.to but for that i need ur help in code modification.

i will donate u $$ for this modification

we can have private chat 

here is my skype id:  blackhatwulf

**Comment by HDVinnie** [comment]
As you were told this is not for public use let alone a scraper. Also opening a issue for something like this is invalid.
