### ISSUE TITLE
Already Downloaded File Indicator

### ISSUE THREAD

**Issue by Red227** [UNIT3D/UNIT3D#64]
**Suggestion**
Making it so that there is an indicator on torrent list of torrents that you have already downloaded that is visible on both Default and Dark Theme.

**Comment by HDVinnie** [comment]
Downloaded as in the torrent file itself? Or 100% of the torrent was downloaded and thus completed?

**Comment by Red227** [comment]
You could do both I suppose, but I was thinking the torrent file itself. To prevent from redownloading it later by accident.
