### ISSUE TITLE
Groups Permission Problem

### ISSUE THREAD

**Issue by drt420** [UNIT3D/UNIT3D#79]
Hello
There is groups permission issue with this code like :

1. Only Uploaders should be able to upload on site. Currently I have made a dirty fix by adding $user->can_upload=0 in app/Http/Controllers/Auth/RegisterController.php. 

2. Validating users are able to upload torrent and also able to sent invite and comment on torrents.

**Comment by HDVinnie** [comment]
> Only Uploaders should be able to upload on site. Currently I have made a dirty fix by adding $user->can_upload=0 in app/Http/Controllers/Auth/RegisterController.php.

That is opinionated. That is the whole point of having the moderation system. All can upload but get stopped for approval before posting to tracker. There is permission to have groups bypass moderation as well. Your "wanted" change will not be implemented.

> Validating users are able to upload torrent and also able to sent invite and comment on torrents.

I am not able to replicate this. Validating members are blocked from view in the /resources/views/layout/default.blade.php at line 340. However I will block them from logging in until there account is activated.
