### ISSUE TITLE
Migration fails on installation

### ISSUE THREAD

**Issue by rickfo97** [UNIT3D/UNIT3D#9]
- Laravel Version: 5.4.*
- PHP Version: 7.0.22-0
- Database Driver & Version: mysql 5.7.20-0

### Description:
When you run step 7 in the installation the migration fails on "2017_12_10_020753_create_achievement_details_table.php" because table already exists.
It is created in "vendor/gstt/laravel-achievements/src/Migrations/0000_00_00_000000_create_achievements_tables.php"

### Steps To Reproduce:
Follow the installation guide.

### Possible Fix:
Remove "2017_12_10_020753_create_achievement_details_table.php" & "2017_12_10_020753_create_achievement_progress_table.php" from "database/migrations/"

**Comment by HDVinnie** [comment]
Solved See ca490ba7558fca0dcbce02b097b124c343bb8b93

**Comment by poppabear8883** [comment]
This is not fixed. The `AddForeignKeysToAchievementProgressTable` must be removed also. Reopening and will push the fix.
