### ISSUE TITLE
Automatically send a PM to user if an H&R warning is imminent. 

### ISSUE THREAD

**Issue by ScroogeHD117** [UNIT3D/UNIT3D#99]
This is a feature request.

The idea is basically for the system to send a user a PM notification or warning that an H&R warning is imminent for a specific torrent if the user goes without seeding it for another X hours.

Example: a tracker requires a user to seed a torrent for 7 days and allows a user to be disconnected for 3 days. There is a user that downloads a torrent and seeds it for 5 days and then disconnects for whatever reason. Once the user has been disconnected for more than 48 hours, the system automatically sends him a warning that he will receive an H&R warning if he does not start seeding the torrent again within 24 hours.

The goal of this feature is to avoid having people get an H&R because they forgot or did not notice that a torrent required more seeding.

**Comment by Darkspace10** [comment]
good feature
